#!/usr/bin/env python
# coding: utf-8

# In[ ]:


# -*- coding: utf-8 -*-
"""app
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1eSCj5d3jp7le-PyZYLvcArQWCQOEiv6Z
"""

import pandas
from flask import jsonify, make_response
from flask import json

from flask import Flask, request, jsonify, render_template
import pickle


app = Flask(__name__)
@app.route('/')
def hello():
    return "Hello World!"

# start flask
app = Flask(__name__)



output=open(r'C:\Users\Win\Downloads\23.Self Case Study-1\lgbm_rep_kfold.sav','rb')
outputdf=pickle.load(output, encoding='bytes')

result={}


# render default webpage
@app.route('/')

def indx():
    return render_template('index.html')

# when the post method detect, then redirect to predict function
@app.route('/predict', methods=['POST'])
def predict():
    predict = request.form.to_dict()
    cardid=  predict.get('CardID')
    print("card_id value is     ",cardid)
    try:
        df=pandas.DataFrame(outputdf, columns =['card_id', 'target'])
        df.set_index('card_id',  inplace = True) 
        result = df.loc[cardid]
        CardId=result.get('card_id')
        score=result.get('target')
        print("score is     ",score)
        return jsonify("loyality score is :" , score)
    except:
        return jsonify('USER IS NOT FOUND')

# get the data for the requested query
if __name__=='__main__':
    app.run(port=8080,debug=True)

